"""
sql_service.py
Classifies and validates SQL generated by the AI before it ever
touches the database.

Every generated statement passes through here. Nothing in this file
talks to the user directly - it raises SqlSafetyError with a plain,
friendly message that main.py forwards as-is, and returns a
QueryType so main.py knows whether to run it immediately or ask for
confirmation first.
"""

import re
from enum import Enum
from typing import List

from .database import ALLOWED_TABLES


class QueryType(str, Enum):
    SELECT = "select"
    MODIFY = "modify"


class SqlSafetyError(Exception):
    """Raised when a generated statement is unsafe or out of scope.
    The message is written to be shown to the end user as-is."""
    pass


# Statements/keywords that are never allowed, no matter what the user asked.
_BLOCKED_PATTERNS = [
    r"\bGRANT\b",
    r"\bREVOKE\b",
    r"\bCREATE\s+USER\b",
    r"\bDROP\s+USER\b",
    r"\bALTER\s+USER\b",
    r"\bSET\s+GLOBAL\b",
    r"\bSET\s+SESSION\b",
    r"\bSHUTDOWN\b",
    r"\bINTO\s+OUTFILE\b",
    r"\bINTO\s+DUMPFILE\b",
    r"\bLOAD_FILE\s*\(",
    r"\bLOAD\s+DATA\b",
    r"\bINFORMATION_SCHEMA\b",
    r"\bMYSQL\.\w+\b",
    r"\bPERFORMANCE_SCHEMA\b",
    r"\bSYS\.\w+\b",
    r"--",
    r"/\*",
    r"\bxp_cmdshell\b",
]

_SELECT_PREFIXES = ("SELECT", "SHOW", "DESCRIBE", "DESC", "EXPLAIN")
_MODIFY_PREFIXES = ("INSERT", "UPDATE", "DELETE", "CREATE", "ALTER", "DROP", "TRUNCATE", "REPLACE")

_TABLE_TOKEN_RE = re.compile(r"\b([a-zA-Z_][a-zA-Z0-9_]*)\b")


def _strip_and_check_single_statement(sql: str) -> str:
    sql = sql.strip()
    # Remove one single trailing semicolon, if present, before checking
    # for stacked statements.
    trimmed = sql[:-1] if sql.endswith(";") else sql
    if ";" in trimmed:
        raise SqlSafetyError(
            "I can only run one database operation at a time, so I wasn't able to complete that request safely."
        )
    return trimmed.strip()


def classify_and_validate(sql: str) -> QueryType:
    """Classify a generated SQL statement and validate it is safe and
    in-scope. Raises SqlSafetyError if it should not be run at all.
    """
    if not sql or not sql.strip():
        raise SqlSafetyError("I wasn't able to turn that into a database request. Could you rephrase it?")

    cleaned = _strip_and_check_single_statement(sql)
    upper = cleaned.upper()

    for pattern in _BLOCKED_PATTERNS:
        if re.search(pattern, upper):
            raise SqlSafetyError(
                "That request involves an administrative operation I'm not allowed to perform."
            )

    first_word = upper.split(None, 1)[0] if upper.split() else ""

    if first_word in _SELECT_PREFIXES:
        query_type = QueryType.SELECT
    elif first_word in _MODIFY_PREFIXES:
        query_type = QueryType.MODIFY
    else:
        raise SqlSafetyError(
            "I wasn't able to safely process that request. Could you rephrase it?"
        )

    _check_tables_in_scope(cleaned)

    return query_type


def _check_tables_in_scope(sql: str) -> None:
    """Best-effort guard: make sure the statement only mentions tables
    CampusQuery AI is allowed to touch (students, courses, departments).
    This is a safety net on top of the LLM prompt, not a full SQL parser.
    """
    upper = sql.upper()
    allowed_upper = [t.upper() for t in ALLOWED_TABLES]

    # Look specifically at the table names following common SQL keywords
    # that introduce a table reference.
    table_ref_re = re.compile(
        r"\b(?:FROM|JOIN|INTO|UPDATE|TABLE)\s+`?([a-zA-Z_][a-zA-Z0-9_]*)`?",
        re.IGNORECASE,
    )
    referenced = table_ref_re.findall(sql)

    for table in referenced:
        if table.upper() not in allowed_upper:
            raise SqlSafetyError(
                "That request refers to information outside the college database I have access to."
            )


def describe_modification(sql: str, query_type: QueryType) -> str:
    """Fallback plain-language description of a pending modification,
    used only if the AI service doesn't supply one. Deliberately vague
    but honest - it names the operation without exposing SQL.
    """
    upper = sql.upper()
    if upper.startswith("INSERT"):
        return "This will add a new record to the college database."
    if upper.startswith("UPDATE"):
        return "This will update existing records in the college database."
    if upper.startswith("DELETE"):
        return "This will delete records from the college database."
    if upper.startswith("TRUNCATE"):
        return "This will remove all records from a table in the college database."
    if upper.startswith("DROP"):
        return "This will remove a table from the college database structure."
    if upper.startswith("ALTER"):
        return "This will change the structure of a table in the college database."
    if upper.startswith("CREATE"):
        return "This will create a new table in the college database."
    return "This will make a change to the college database."
